COMMON_FUNC="/dlmp/sandbox/cgslIS/LPEA_CAD_PIPELINE_UTILITIES/src/main/bash/commonFunctions.sh"
ILLUMINA_WRAPPER_SCRIPT="/dlmp/sandbox/cgslIS/NGS_RUGD/src/bash/illumina-wgs-cli-wrapper.sh"
PYTHON="/biotools/biotools/python/3.6.3/bin/python"
QDIR="/usr/local/biotools/oge/ge2011.11/bin/linux-x64"
QSUB="${QDIR}/qsub"
QSTAT="${QDIR}/qstat"
LOG_DIR="/dlmp/sandbox/cgslIS/Yuta/logs"
QSUB_ARGS="-terse -V -q sandbox.q -l h_vmem=40G -o ${LOG_DIR} -j y"